version: "3.8"

services:
  redis:
    image: redis:6.2.3-alpine
    # command: redis-server --requirepass ${REDIS_PASS} --appendonly yes
    volumes:
      - ./temp/local/redis:/data
    ports:
      - 6379:6379